"""Static contracts and defaults for the Yuanli governance system."""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOCAL_TIMEZONE = "Asia/Shanghai"

ENTITY_FILES = {
    "spaces": PROJECT_ROOT / "canonical" / "entities" / "spaces.json",
    "subjects": PROJECT_ROOT / "canonical" / "entities" / "subjects.json",
    "endpoints": PROJECT_ROOT / "canonical" / "entities" / "endpoints.json",
    "accounts": PROJECT_ROOT / "canonical" / "entities" / "accounts.json",
    "operating_modules": PROJECT_ROOT / "canonical" / "entities" / "operating_modules.json",
    "source_feeds": PROJECT_ROOT / "canonical" / "entities" / "source_feeds.json",
    "ingestion_runs": PROJECT_ROOT / "canonical" / "entities" / "ingestion_runs.json",
    "assets": PROJECT_ROOT / "canonical" / "entities" / "assets.json",
    "orders": PROJECT_ROOT / "canonical" / "entities" / "orders.json",
    "cashflows": PROJECT_ROOT / "canonical" / "entities" / "cashflows.json",
    "tasks": PROJECT_ROOT / "canonical" / "entities" / "tasks.json",
    "threads": PROJECT_ROOT / "canonical" / "entities" / "threads.json",
    "skills": PROJECT_ROOT / "canonical" / "entities" / "skills.json",
    "decision_records": PROJECT_ROOT / "canonical" / "entities" / "decision_records.json",
    "actions": PROJECT_ROOT / "canonical" / "entities" / "actions.json",
    "agent_capabilities": PROJECT_ROOT / "canonical" / "entities" / "agent_capabilities.json",
    "writeback_events": PROJECT_ROOT / "canonical" / "entities" / "writeback_events.json",
    "knowledge_sources": PROJECT_ROOT / "canonical" / "entities" / "knowledge_sources.json",
    "knowledge_items": PROJECT_ROOT / "canonical" / "entities" / "knowledge_items.json",
    "review_runs": PROJECT_ROOT / "canonical" / "entities" / "review_runs.json",
    "relations": PROJECT_ROOT / "canonical" / "relations" / "relations.json",
}

FIXED_RELATION_TYPES = [
    "space_contains_subject",
    "space_contains_module",
    "space_parent_of_space",
    "subject_owns_endpoint",
    "endpoint_hosts_account",
    "subject_controls_account",
    "subject_responsible_for_module",
    "ai_agent_copilots_module",
    "ai_deputy_oversees_module",
    "skill_enables_agent",
    "asset_supports_account",
    "asset_supports_module",
    "task_targets_subject",
    "task_targets_module",
    "thread_tracks_space",
    "asset_supports_task",
    "task_belongs_to_thread",
    "skill_supports_task",
    "skill_supports_thread",
    "asset_supports_thread",
]

BUSINESS_DEPUTY_SUBJECT_ID = "subject-agent-business-deputy"
BUSINESS_MODULE_CODES = ("public", "private", "sales")

CLUSTER_DEFAULTS = {
    "AI大管家治理簇": {
        "verification_strength": 5,
        "cost_efficiency": 4,
        "auth_reuse": 2,
        "complexity_penalty": 1,
    },
    "平台簇": {
        "verification_strength": 4,
        "cost_efficiency": 4,
        "auth_reuse": 3,
        "complexity_penalty": 2,
    },
    "垂直workflow簇": {
        "verification_strength": 4,
        "cost_efficiency": 4,
        "auth_reuse": 2,
        "complexity_penalty": 2,
    },
    "技能生产簇": {
        "verification_strength": 4,
        "cost_efficiency": 4,
        "auth_reuse": 1,
        "complexity_penalty": 2,
    },
    "agency簇": {
        "verification_strength": 2,
        "cost_efficiency": 3,
        "auth_reuse": 1,
        "complexity_penalty": 2,
    },
    "未分组": {
        "verification_strength": 3,
        "cost_efficiency": 3,
        "auth_reuse": 1,
        "complexity_penalty": 2,
    },
}

FEDERATION_SPACE_SPECS = [
    {
        "id": "space-federation-root",
        "space_id": "space-federation-root",
        "title": "原理OS联邦总图",
        "space_type": "federation_root",
        "parent_space_id": "",
        "status": "active",
        "owner_mode": "hybrid",
        "description": "联邦治理总图，只汇总不吞掉实例边界。",
        "federation_role": "root",
        "source_ref": "generated://federation-root",
        "confidence": 0.96,
    },
    {
        "id": "space-personal-zero",
        "space_id": "space-personal-zero",
        "title": "0号实例-你本人",
        "space_type": "personal_instance",
        "parent_space_id": "space-federation-root",
        "status": "active",
        "owner_mode": "human",
        "description": "你的本地治理实例，承接终端、账号和日常协作。",
        "federation_role": "personal",
        "source_ref": "generated://space/personal-zero",
        "confidence": 0.95,
    },
    {
        "id": "space-internal-team",
        "space_id": "space-internal-team",
        "title": "内部协作实例",
        "space_type": "internal_instance",
        "parent_space_id": "space-federation-root",
        "status": "active",
        "owner_mode": "hybrid",
        "description": "同事与合伙人的责任协同空间。",
        "federation_role": "internal",
        "source_ref": "generated://space/internal-team",
        "confidence": 0.9,
    },
    {
        "id": "space-client-template",
        "space_id": "space-client-template",
        "title": "客户复制实例",
        "space_type": "client_instance",
        "parent_space_id": "space-federation-root",
        "status": "planned",
        "owner_mode": "hybrid",
        "description": "客户复制这套治理模型的样板空间。",
        "federation_role": "client",
        "source_ref": "generated://space/client-template",
        "confidence": 0.88,
    },
    {
        "id": "space-downstream-template",
        "space_id": "space-downstream-template",
        "title": "下游复制实例",
        "space_type": "downstream_instance",
        "parent_space_id": "space-federation-root",
        "status": "planned",
        "owner_mode": "hybrid",
        "description": "客户的客户沿用这套模型时的下游空间。",
        "federation_role": "downstream",
        "source_ref": "generated://space/downstream-template",
        "confidence": 0.85,
    },
]

DEFAULT_SUBJECT_SPECS = [
    {
        "id": "subject-hay2045",
        "subject_id": "subject-hay2045",
        "title": "hay2045",
        "subject_type": "human",
        "space_id": "space-personal-zero",
        "status": "active",
        "owner_mode": "human",
        "autonomy_tier": "human_owner",
        "responsibility_scope": ["public", "private", "governance"],
        "source_ref": "generated://subject/hay2045",
        "confidence": 0.96,
    },
    {
        "id": "subject-collab-owner",
        "subject_id": "subject-collab-owner",
        "title": "内部协作责任人",
        "subject_type": "human",
        "space_id": "space-internal-team",
        "status": "active",
        "owner_mode": "human",
        "autonomy_tier": "human_delegate",
        "responsibility_scope": ["sales", "delivery", "finance"],
        "source_ref": "generated://subject/internal-owner",
        "confidence": 0.88,
    },
    {
        "id": "subject-internal-org",
        "subject_id": "subject-internal-org",
        "title": "原力内部组织",
        "subject_type": "org",
        "space_id": "space-internal-team",
        "status": "active",
        "owner_mode": "hybrid",
        "autonomy_tier": "org_boundary",
        "responsibility_scope": ["sales", "delivery", "finance", "governance"],
        "source_ref": "generated://subject/internal-org",
        "confidence": 0.9,
    },
    {
        "id": "subject-client-org-template",
        "subject_id": "subject-client-org-template",
        "title": "客户组织样板",
        "subject_type": "client_org",
        "space_id": "space-client-template",
        "status": "planned",
        "owner_mode": "hybrid",
        "autonomy_tier": "client_boundary",
        "responsibility_scope": ["public", "private", "sales", "delivery"],
        "source_ref": "generated://subject/client-template",
        "confidence": 0.85,
    },
    {
        "id": "subject-downstream-client-template",
        "subject_id": "subject-downstream-client-template",
        "title": "客户的客户样板",
        "subject_type": "client_org",
        "space_id": "space-downstream-template",
        "status": "planned",
        "owner_mode": "hybrid",
        "autonomy_tier": "downstream_boundary",
        "responsibility_scope": ["public", "private", "sales"],
        "source_ref": "generated://subject/downstream-template",
        "confidence": 0.82,
    },
]

OPERATING_MODULE_SPECS = [
    {
        "id": "module-public",
        "module_id": "module-public",
        "title": "公域获客",
        "module_code": "public",
        "module_type": "cbm",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_subject_id": "subject-hay2045",
        "ai_subject_id": "subject-agent-public",
        "deputy_subject_id": BUSINESS_DEPUTY_SUBJECT_ID,
        "kpi_hint": "流量、触达、线索输入",
        "source_ref": "generated://module/public",
        "confidence": 0.95,
    },
    {
        "id": "module-private",
        "module_id": "module-private",
        "title": "私域转化",
        "module_code": "private",
        "module_type": "cbm",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_subject_id": "subject-hay2045",
        "ai_subject_id": "subject-agent-private",
        "deputy_subject_id": BUSINESS_DEPUTY_SUBJECT_ID,
        "kpi_hint": "线索状态、转化节奏、复购机会",
        "source_ref": "generated://module/private",
        "confidence": 0.95,
    },
    {
        "id": "module-sales",
        "module_id": "module-sales",
        "title": "销售成交",
        "module_code": "sales",
        "module_type": "cbm",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_subject_id": "subject-collab-owner",
        "ai_subject_id": "subject-agent-sales",
        "deputy_subject_id": BUSINESS_DEPUTY_SUBJECT_ID,
        "kpi_hint": "商机推进、报价、成交额",
        "source_ref": "generated://module/sales",
        "confidence": 0.94,
    },
    {
        "id": "module-delivery",
        "module_id": "module-delivery",
        "title": "产品交付",
        "module_code": "delivery",
        "module_type": "cbm",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_subject_id": "subject-collab-owner",
        "ai_subject_id": "subject-agent-delivery",
        "deputy_subject_id": "",
        "kpi_hint": "交付节奏、里程碑、满意度",
        "source_ref": "generated://module/delivery",
        "confidence": 0.94,
    },
    {
        "id": "module-finance",
        "module_id": "module-finance",
        "title": "财务经营",
        "module_code": "finance",
        "module_type": "cbm",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_subject_id": "subject-collab-owner",
        "ai_subject_id": "subject-agent-finance",
        "deputy_subject_id": "",
        "kpi_hint": "回款、利润、现金流",
        "source_ref": "generated://module/finance",
        "confidence": 0.94,
    },
    {
        "id": "module-governance",
        "module_id": "module-governance",
        "title": "治理控制",
        "module_code": "governance",
        "module_type": "cbm",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_subject_id": "subject-hay2045",
        "ai_subject_id": "subject-agent-governance",
        "deputy_subject_id": "",
        "kpi_hint": "闭环率、失真率、复制进度",
        "source_ref": "generated://module/governance",
        "confidence": 0.97,
    },
]

DEFAULT_AGENT_SPECS = [
    {
        "id": BUSINESS_DEPUTY_SUBJECT_ID,
        "subject_id": BUSINESS_DEPUTY_SUBJECT_ID,
        "title": "业务增长 Deputy",
        "subject_type": "ai_agent",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_mode": "ai",
        "autonomy_tier": "deputy",
        "responsibility_scope": list(BUSINESS_MODULE_CODES),
        "source_ref": "generated://subject-agent/business-deputy",
        "confidence": 0.95,
    },
    {
        "id": "subject-agent-public",
        "subject_id": "subject-agent-public",
        "title": "公域增长 Agent",
        "subject_type": "ai_agent",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_mode": "ai",
        "autonomy_tier": "copilot",
        "responsibility_scope": ["public"],
        "source_ref": "generated://subject-agent/public",
        "confidence": 0.94,
    },
    {
        "id": "subject-agent-private",
        "subject_id": "subject-agent-private",
        "title": "私域转化 Agent",
        "subject_type": "ai_agent",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_mode": "ai",
        "autonomy_tier": "copilot",
        "responsibility_scope": ["private"],
        "source_ref": "generated://subject-agent/private",
        "confidence": 0.94,
    },
    {
        "id": "subject-agent-sales",
        "subject_id": "subject-agent-sales",
        "title": "销售 Agent",
        "subject_type": "ai_agent",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_mode": "ai",
        "autonomy_tier": "copilot",
        "responsibility_scope": ["sales"],
        "source_ref": "generated://subject-agent/sales",
        "confidence": 0.94,
    },
    {
        "id": "subject-agent-delivery",
        "subject_id": "subject-agent-delivery",
        "title": "交付 Agent",
        "subject_type": "ai_agent",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_mode": "ai",
        "autonomy_tier": "copilot",
        "responsibility_scope": ["delivery"],
        "source_ref": "generated://subject-agent/delivery",
        "confidence": 0.94,
    },
    {
        "id": "subject-agent-finance",
        "subject_id": "subject-agent-finance",
        "title": "财务 Agent",
        "subject_type": "ai_agent",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_mode": "ai",
        "autonomy_tier": "copilot",
        "responsibility_scope": ["finance"],
        "source_ref": "generated://subject-agent/finance",
        "confidence": 0.94,
    },
    {
        "id": "subject-agent-governance",
        "subject_id": "subject-agent-governance",
        "title": "治理 Agent",
        "subject_type": "ai_agent",
        "space_id": "space-federation-root",
        "status": "active",
        "owner_mode": "ai",
        "autonomy_tier": "copilot",
        "responsibility_scope": ["governance"],
        "source_ref": "generated://subject-agent/governance",
        "confidence": 0.97,
    },
]

DEFAULT_ENDPOINT_SPECS = [
    {
        "id": "endpoint-local-workstation",
        "endpoint_id": "endpoint-local-workstation",
        "title": "本地工作站",
        "endpoint_type": "workstation",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "active",
        "health_status": "healthy",
        "source_ref": "generated://endpoint/local-workstation",
        "confidence": 0.95,
    },
    {
        "id": "endpoint-terminal-a",
        "endpoint_id": "endpoint-terminal-a",
        "title": "终端A",
        "endpoint_type": "terminal",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "active",
        "health_status": "healthy",
        "source_ref": "generated://endpoint/terminal-a",
        "confidence": 0.92,
    },
    {
        "id": "endpoint-terminal-b",
        "endpoint_id": "endpoint-terminal-b",
        "title": "终端B",
        "endpoint_type": "terminal",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "active",
        "health_status": "healthy",
        "source_ref": "generated://endpoint/terminal-b",
        "confidence": 0.92,
    },
    {
        "id": "endpoint-terminal-c",
        "endpoint_id": "endpoint-terminal-c",
        "title": "终端C",
        "endpoint_type": "terminal",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "planned",
        "health_status": "planned",
        "source_ref": "generated://endpoint/terminal-c",
        "confidence": 0.9,
    },
    {
        "id": "endpoint-feishu-mobile",
        "endpoint_id": "endpoint-feishu-mobile",
        "title": "飞书手机端",
        "endpoint_type": "mobile",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "planned",
        "health_status": "planned",
        "source_ref": "generated://endpoint/feishu-mobile",
        "confidence": 0.88,
    },
]

DEFAULT_ACCOUNT_SPECS = [
    {
        "id": "account-github",
        "account_id": "account-github",
        "title": "GitHub 主账号",
        "account_type": "developer_platform",
        "platform": "GitHub",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "active",
        "health_status": "healthy",
        "channel_role": "governance",
        "endpoint_id": "endpoint-local-workstation",
        "source_ref": "generated://account/github",
        "confidence": 0.95,
    },
    {
        "id": "account-feishu",
        "account_id": "account-feishu",
        "title": "Feishu 主账号",
        "account_type": "collaboration",
        "platform": "Feishu",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "active",
        "health_status": "healthy",
        "channel_role": "governance",
        "endpoint_id": "endpoint-feishu-mobile",
        "source_ref": "generated://account/feishu",
        "confidence": 0.94,
    },
    {
        "id": "account-wechat",
        "account_id": "account-wechat",
        "title": "微信主号",
        "account_type": "social",
        "platform": "WeChat",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "planned",
        "health_status": "needs_inventory",
        "channel_role": "private",
        "endpoint_id": "endpoint-feishu-mobile",
        "source_ref": "generated://account/wechat",
        "confidence": 0.86,
    },
    {
        "id": "account-video-channel",
        "account_id": "account-video-channel",
        "title": "视频号阵地",
        "account_type": "content_channel",
        "platform": "Video Channel",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "planned",
        "health_status": "needs_inventory",
        "channel_role": "public",
        "endpoint_id": "endpoint-feishu-mobile",
        "source_ref": "generated://account/video-channel",
        "confidence": 0.84,
    },
    {
        "id": "account-bilibili",
        "account_id": "account-bilibili",
        "title": "B站阵地",
        "account_type": "content_channel",
        "platform": "Bilibili",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "planned",
        "health_status": "needs_inventory",
        "channel_role": "public",
        "endpoint_id": "endpoint-terminal-a",
        "source_ref": "generated://account/bilibili",
        "confidence": 0.84,
    },
    {
        "id": "account-douyin",
        "account_id": "account-douyin",
        "title": "抖音阵地",
        "account_type": "content_channel",
        "platform": "Douyin",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "planned",
        "health_status": "needs_inventory",
        "channel_role": "public",
        "endpoint_id": "endpoint-terminal-b",
        "source_ref": "generated://account/douyin",
        "confidence": 0.84,
    },
    {
        "id": "account-xiaohongshu",
        "account_id": "account-xiaohongshu",
        "title": "小红书阵地",
        "account_type": "content_channel",
        "platform": "Xiaohongshu",
        "space_id": "space-personal-zero",
        "owner_subject_id": "subject-hay2045",
        "status": "planned",
        "health_status": "needs_inventory",
        "channel_role": "public",
        "endpoint_id": "endpoint-terminal-c",
        "source_ref": "generated://account/xiaohongshu",
        "confidence": 0.84,
    },
]

AGENT_SKILL_HINTS = {
    "subject-agent-governance": ["ai-da-guan-jia", "knowledge-orchestrator"],
    BUSINESS_DEPUTY_SUBJECT_ID: ["knowledge-orchestrator", "yuanli-core", "feishu-bitable-bridge"],
    "subject-agent-public": ["yuanli-core", "yuanli-xiaoshitou", "openclaw-xhs-coevolution-lab"],
    "subject-agent-private": ["knowledge-orchestrator", "feishu-bitable-bridge"],
    "subject-agent-sales": ["knowledge-orchestrator", "agency-data-consolidation-agent"],
    "subject-agent-delivery": ["yuanli-core", "yuanli-zsxq-coevolution-assistant"],
    "subject-agent-finance": ["agency-support-finance-tracker"],
}

FEISHU_TABLE_SPECS = [
    {
        "table_id": "spaces",
        "table_name": "联邦实例表",
        "primary_field": "实例ID",
        "fields": [
            "标题",
            "实例类型",
            "上级实例",
            "联邦角色",
            "状态",
            "拥有方式",
            "说明",
            "置信度",
        ],
    },
    {
        "table_id": "subjects",
        "table_name": "主体总表",
        "primary_field": "主体ID",
        "fields": [
            "标题",
            "主体类型",
            "所属实例",
            "自治层级",
            "负责模块",
            "状态",
            "拥有方式",
            "置信度",
        ],
    },
    {
        "table_id": "endpoints",
        "table_name": "终端表",
        "primary_field": "终端ID",
        "fields": [
            "标题",
            "终端类型",
            "所属实例",
            "拥有主体",
            "健康状态",
            "状态",
            "置信度",
        ],
    },
    {
        "table_id": "accounts",
        "table_name": "终端账号表",
        "primary_field": "账号ID",
        "fields": [
            "标题",
            "平台",
            "账号类型",
            "所属实例",
            "拥有主体",
            "渠道角色",
            "宿主终端",
            "健康状态",
            "状态",
            "置信度",
        ],
    },
    {
        "table_id": "operating_modules",
        "table_name": "CBM模块责任表",
        "primary_field": "模块ID",
        "fields": [
            "标题",
            "模块编码",
            "所属实例",
            "人类Owner",
            "AI Copilot",
            "KPI提示",
            "状态",
            "置信度",
        ],
    },
    {
        "table_id": "source_feeds",
        "table_name": "来源总表",
        "primary_field": "来源ID",
        "fields": [
            "标题",
            "来源族",
            "注册分组",
            "根路径",
            "宿主设备",
            "关联账号",
            "状态",
            "识别文件数",
            "未分类文件数",
            "最后扫描时间",
        ],
    },
    {
        "table_id": "ingestion_runs",
        "table_name": "采集运行表",
        "primary_field": "运行ID",
        "fields": [
            "运行类型",
            "状态",
            "扫描文件数",
            "识别文件数",
            "订单数",
            "现金流数",
            "内容资产数",
            "未分类文件数",
            "敏感检查状态",
            "运行时间",
        ],
    },
    {
        "table_id": "assets",
        "table_name": "资产总表",
        "primary_field": "资产ID",
        "fields": [
            "标题",
            "资产类型",
            "领域",
            "来源路径",
            "来源类型",
            "内容分类",
            "来源族",
            "模块编码",
            "关联账号",
            "来源设备",
            "敏感级别",
            "校验指纹",
            "解析状态",
            "状态",
            "拥有方式",
            "置信度",
            "最后发现时间",
        ],
    },
    {
        "table_id": "orders",
        "table_name": "订单事实表",
        "primary_field": "订单ID",
        "fields": [
            "订单日期",
            "支付金额",
            "支付平台",
            "订单来源",
            "客户名称",
            "手机号",
            "服务线",
            "主转化归属",
            "次转化归属",
            "来源族",
            "敏感级别",
        ],
    },
    {
        "table_id": "cashflows",
        "table_name": "现金流事实表",
        "primary_field": "流水ID",
        "fields": [
            "发生日期",
            "金额",
            "方向",
            "账户",
            "对手方",
            "摘要",
            "来源族",
            "敏感级别",
            "解析状态",
        ],
    },
    {
        "table_id": "content_assets",
        "table_name": "内容资产表",
        "primary_field": "资产ID",
        "fields": [
            "标题",
            "内容分类",
            "来源族",
            "来源路径",
            "关联账号",
            "模块编码",
            "解析状态",
            "敏感级别",
            "最后发现时间",
        ],
    },
    {
        "table_id": "tasks",
        "table_name": "任务总表",
        "primary_field": "任务ID",
        "fields": [
            "标题",
            "目标ID",
            "状态",
            "优先级",
            "拥有方式",
            "调用技能",
            "验真状态",
            "证据引用",
            "下一步动作",
            "最后更新时间",
        ],
    },
    {
        "table_id": "threads",
        "table_name": "线程总表",
        "primary_field": "线程ID",
        "fields": [
            "标题",
            "主题",
            "目标ID",
            "状态",
            "来源运行ID",
            "开放问题",
            "晨会关注",
            "下次复盘日期",
        ],
    },
    {
        "table_id": "skills",
        "table_name": "技能能力表",
        "primary_field": "技能ID",
        "fields": [
            "技能名",
            "簇",
            "角色",
            "验真强度",
            "成本效率",
            "登录态复用",
            "复杂度惩罚",
            "状态",
            "路由信用",
        ],
    },
    {
        "table_id": "review_runs",
        "table_name": "专项晨会记录表",
        "primary_field": "Review ID",
        "fields": [
            "复盘日期",
            "范围",
            "摘要",
            "主要风险",
            "候选动作",
            "待你拍板",
            "同步状态",
        ],
    },
]

DASHBOARD_QUESTIONS = [
    "联邦体系里现在有哪些主体与实例边界？",
    "终端与账号阵地覆盖到什么程度，哪里失管？",
    "CBM 模块的人类 Owner 与 AI Copilot 是否齐备？",
    "AI 编制是否形成 Agent + Skill 双层挂接？",
    "当前最重要的活跃线程是什么？",
    "哪些任务在推进，堵点在哪里？",
    "哪些技能在高频使用，哪里存在能力缺口？",
    "客户复制实例推进到哪一层了？",
    "原力治理系统正在往哪个战略目标进化？",
]

MORNING_REVIEW_SECTIONS = [
    "今日结构变化",
    "外部线索摘要",
    "当前最值得关注的问题",
    "3 个候选进化动作",
    "当前等待你做的选择",
]
